Fix file type attr
sulu/SuluFormBundle pull request #328
Opened 2022-07-14 12:58 UTC by RealAestan

| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #issuenum
| Related issues/PRs | #issuenum
| License | MIT

#### What's in this PR?

The attribute max is removed on input type file
The attribute accept is removed when there is not restrictions on input file type

#### Why?

max attr is no only applicable on `date` `month` `week` `time` `datetime-local` `number` `range` input types
accept attr should not be empty, when all files are accepted the attribute should be removed

2022-07-14 15:02 UTC, alexander-schranz requested changes
Thx for the pull request. Little change request.

2022-07-14 15:02 UTC, alexander-schranz commented on Dynamic/Types/AttachmentType.php
> -            $options['attr']['max'] = $fileMax;
Remove this would be a bc break and would crash form themes try to read this attribute to be displayed as value on the website.

At current state we can only add a comment to `// @deprecated` this and add a line to the `UPGRADE.md` to remove it in the next major.

For your website you can filter out that attribute in your custom form theme if you don't want to render it.

2022-07-14 15:02 UTC, alexander-schranz commented on Dynamic/Types/AttachmentType.php
> +        }
👍

2022-07-14 19:46 UTC, RealAestan commented on Dynamic/Types/AttachmentType.php
> -            $options['attr']['max'] = $fileMax;
Hello, my bad I totally forgot that use case. I added a new "data-max" attribute to allow people who have this use case to have this possibility. Should I add something to UPGRADE.md or let you handle it when you will prepare the release ?

2022-07-14 19:51 UTC, alexander-schranz commented on Dynamic/Types/AttachmentType.php
> -            $options['attr']['max'] = $fileMax;
yeah a sentence in the UPGRADE.md would be great about it.

2024-04-30 09:02 UTC, alexander-schranz commented on Dynamic/Types/AttachmentType.php
> +            // TODO : Remove when a new major is release and tell user to migrate to data-max attribute
```suggestion
            // @deprecated remove when a new major is release as max is not supported by input[type=file]
```

2024-04-30 09:04 UTC, merged

2024-04-30 09:04 UTC, alexander-schranz commented
@RealAestan Thank you!